function(testcoe_enable_static_mingw_runtime target_name)
    if(MINGW)
        target_link_options(${target_name} PRIVATE -static)
    endif()
endfunction()

function(testcoe_enable_strict_warnings target_name)
    if(MSVC)
        target_compile_options(${target_name} PRIVATE /W4 /WX)
    else()
        target_compile_options(${target_name} PRIVATE -Werror -Wall -Wextra -Wpedantic)
    endif()
endfunction()

function(testcoe_ignore_external_warnings target_name)
    if(TARGET ${target_name})
        get_target_property(include_dirs ${target_name} INTERFACE_INCLUDE_DIRECTORIES)
        if(include_dirs)
            set_target_properties(${target_name} PROPERTIES
                INTERFACE_SYSTEM_INCLUDE_DIRECTORIES "${include_dirs}"
            )
            message(STATUS "[testcoe] Ignoring ${target_name} warnings")
        endif()
    else()
        message(WARNING "[testcoe] Target ${target_name} not found")
    endif()
endfunction()
