name: Windows

on:
    push:
        branches: [main]
    pull_request:
        types: [opened, synchronize, reopened, ready_for_review]
        branches: [main]

jobs:
    build-and-test:
        name: ${{ matrix.name }}
        runs-on: windows-latest
        if: github.event.pull_request.draft == false || github.event_name == 'push'
        strategy:
            fail-fast: false
            matrix:
                include:
                    - name: "Windows MSVC"
                      compiler: msvc
                      cmake-generator: 'Ninja'
                      cmake-options: '-DCMAKE_C_COMPILER=cl -DCMAKE_CXX_COMPILER=cl -DCMAKE_BUILD_TYPE=Release'
                    
                    - name: "Windows MinGW"
                      compiler: gcc
                      cmake-generator: 'MinGW Makefiles'
                      cmake-options: '-DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++'

        steps:
        - name: Checkout repository
          uses: actions/checkout@v3
          with:
            submodules: 'recursive'

        - name: Install Windows build tools
          if: matrix.compiler != 'msvc'
          run: |
            choco install mingw
          shell: bash

        - name: Setup MSVC dev environment
          if: matrix.compiler == 'msvc'
          uses: ilammy/msvc-dev-cmd@v1.13.0

        - name: Configure CMake
          run: |
            cmake -B build -G "${{ matrix.cmake-generator }}" ${{ matrix.cmake-options }} -DTESTCOE_BUILD_EXAMPLES=ON -DTESTCOE_BUILD_TESTS=ON
            
          shell: bash

        - name: Build
          run: |
            cmake --build build --config Release
          shell: bash
        
        - name: Run tests
          working-directory: build
          run: |
            ./tests/testcoe_tests.exe
          shell: bash